### ISSUE TITLE
where is the definition of "dialog-mask" class

### ISSUE THREAD

**Issue by lastboy1228** [hjkcai/vue-modal-dialogs#20]
The demo do not pop up as a modal window, but show up in the place of "dialogs-wrapper" tag.

**Comment by hjkcai** [comment]
Yes, this is correct because **something like `<dialog-mask>` is just a part of the dialog itself**. 

Remember: vue-modal-dialogs manages dialogs. It does not care about how the dialogs look like.
For example ([source](https://github.com/hjkcai/vue-modal-dialogs/blob/examples/src/examples/message-box/dialog.vue)):

```html
<template>
  <div class="message-box dialog-mask" @click="$close">
    <div class="dialog-content">
      <div class="dialog-body">
        <p>{{ content }}</p>
      </div>
      <footer>
        <el-button type="text" size="mini" @click="$close">OK</el-button>
      </footer>
    </div>
  </div>
</template>
```

**Comment by lastboy1228** [comment]
OK, I copied all the dialog-* styles from css file in the demo page.
