### ISSUE TITLE
Not sure how to use $error instead of $close

### ISSUE THREAD

**Issue by highstone** [hjkcai/vue-modal-dialogs#22]
First of all, thanks for this awesome extension. I really like the way it can be included in our application flow, instead of registering all sorts of modals that have their individual ok/cancel actions. It keeps the application flow clear and concise.

A common use-case is to ask for confirmation or additional data. E.g. showing an input field with a OK/Cancel button. Now we return an object on `$close { confirmed: true| false; value: inputValue }`. All good.
It would be awesome, however, if also a `$cancel` method could be provided. Usually nothing needs to happen here, just closing the modal on clicking the close button in the top-right corner or using the Cancel button. And then the `$close` method only needs to provide the input value, instead of including a `confirmed` property

Probably we could also use `$error` for this, but I'm not really sure about it's intended behaviour and how to handle this? Can you add an example for this in the guide?

**Comment by hjkcai** [comment]
In fact `$close` and `$error` are very easy to distinguish.  vue-modal-dialog converts the dialog into a Promise. `$close` and `$error` correspond to the Promise method `resolve` and `reject` respectively. If you want to resolve the Promise which the dialog function has created, call `$close`. Otherwise call `$error`. 

In your case, you could use `InputValue | null` as the value type of the Promise. When the confirm button is clicked, call `$close(this.inputValue)`. When the cancel button is clicked, call `$close(null)`.

I will close the issue now. But please feel free to comment on this issue if you have more questions.
