### ISSUE TITLE
Unable to pass options to the DialogsWrapper component

### ISSUE THREAD

**Issue by Mike-Gibson-Advanced** [hjkcai/vue-modal-dialogs#4]
I ran into an issue when using the [i18n library](https://github.com/kazupon/vue-i18n) with vue-modal-dialogs.

The i18n library expects the component to have an `i18n` property on the root component. This is easy for components in my app as it is passed to the root vue component like:
```
new Vue({
    i18n: i18n,
    el: ...
    store: ...
    router: ...
});
```

But, since components shown as a dialog (after being created by the `makeDialog` function) are childred of the `DialogsWrapper` component, when trying to translate a value, the i18n library is looking for an i18n property on the DialogsWrapper component, which doesn't exist as this is created by the vue-modal-dialogs library and there are no options which will pass this to the component's constructor. 

I tried modifying the line [here](https://github.com/hjkcai/vue-modal-dialogs/blob/628a65396bf67ffa2ff8187411dcd36df0c73e8b/src/index.js#L31) to pass options, like
```
dialogsWrapper = new DialogsWrapper(options.wrapperComponentOptions)
```

and use it by doing
```
Vue.use(ModalDialogs, { wrapperComponentOptions: { i18n: i18n } });
```

and this caused the i18n library to work as expected.

I've not tested it, but there may be similar issues if trying to access for example, a vuex store in a modal dialog. 

Would it be possible to add a configuration option to pass such options to the `DialogsWrapper` component?

Again, I'm happy to help put together a PR.

**Comment by hjkcai** [comment]
Sorry I did not realize creating a new root will cause so much problems. I think this approach is not the best one but will work in most situations. Feel free to send me a PR with your solution. 

I have an idea. Export a `DialogsWrapper` component that can be inserted into the beginning of the "App.vue". Then every dialog will be added into this wrapper automatically. If this idea can be implemented, there will be less duplication in your project 😃.

I am glad to know you like vue-modal-dialogs very much. I will do my best to make this little project better. Please open an issue or a PR immediately if you have any idea about vue-modal-dialogs. Thanks again for helping me with vue-modal-dialogs.

**Comment by hjkcai** [comment]
By the way, how do you think of the APIs of vue-modal-dialogs? I would like to hear more about vue-modal-dialogs from you😁

**Comment by Mike-Gibson-Advanced** [comment]
Interesting thought about exporting the `DialogsWrapper` component, I hadn't thought of that. You're right, it would reduce duplication. I have to admit I'm quite new to vue - I've only been using it for a few months now. If a `DialogsWrapper` component was exported and used in the root vue component, I assume that then the components created by `makeDialog` would have to be children of the DOM element for the DialogsWrapper. This would mean the modal wouldn't be able to be created in a top-level DOM element like it behaves currently. (when `el` isn't specified). For me that's not an issue, as I'm using the bootstrap modal dialog which seems to work this way. I wonder if it's a deal-breaker for people already using the library or other modal libraries?

Yeah I really like the API - really like being able to do e.g. `await confirm("Are you sure?")` and the fact that you can pass any component to the `makeDialog` function 👍 
One minor thing I noticed is that the arguments passed to the function returned from `makeDialog` are order-dependent, I might have liked to be able to pass an object, so rather than
```
const confirm = makeDialog(ConfirmComponent, "title", "question");
await confirm("My title", "My question");
```
you could do
```
const confirm = makeDialog(ConfirmComponent, "title", "question");
await confirm({ title: "My title", question: "My question" });
```
It might also then be able to strongly type the function returned from `makeDialog` in the TypeScript typings (not 100% sure though).

But overall, I do like the API.

**Comment by hjkcai** [comment]
I have had some ideas on implementing the new magic `DialogsWrapper` component right now. As you say, it would not be able to be a top-level element of the DOM. But I think this is OK because some CSS tricks (e.g. `position: fixed`) can be used to 'lift' the dialogs up to the top of any other elements. The position of the wrapper is not so important in this approach. 

By using Bootstrap (v3), you can define the dialog anywhere you want with unchanged dialog behaviors. So I think it is alright to integrate some static CSS libraries like Bootstrap. But what I worry about is compatibility of some UI libraries that designed to use only with Vue (e.g. element-ui). Code to control the behavior of their dialog component is exist. Developers would have to disable (maybe part of) its behavior controlling mechanism before they make a dialog function in vue-modal-dialogs. 

As for the APIs, I am sure there will a big change to the APIs if I turned `DialogsWrapper` into a component. vue-modal-dialogs will become more flexible and can do even more (e.g. notification system). But the core concept of the dialog components and the dialog functions will not change. Also I will improve the typings to make you use vue-modal-dialogs with TypeScript eaiser. You can keep an eye on the upcoming 2.x branch.

There is a problem when passing an 'arguments object' into the dialog function. How do I know whether the first argument is an 'arguments object' or just a single object argument? 

```javascript
const dialog1 = makeDialog(SomeComponent, 'data')
dialog1({ title: 'My title', content: 'My content' })    // seems fine

const dialog2 = makeDialog(SomeOtherComponent, 'title', 'content')
dialog2({ title: 'My title', content: 'My content' })    // oops! 
```

I may not implement this feature in the future versions unless there is a better way to distinguish these two situations. You may need to do this by yourself like this:

```javascript
// component
export default {
  data: () => ({
    title: '',
    question: ''
  }),
  mounted () {
    Object.assign(this, this.arguments[0])
  }
}
```

```typescript
interface ConfirmOptions {
  title: string,
  question: string
}

const confirm: (data: ConfirmOptions) => Promise<boolean> = makeDialog(ConfirmComponent)
await confirm({ title: "My title", question: "My question" })
```

**Comment by hjkcai** [comment]
@Mike-Gibson-Advanced Hey! I have been working on version 2.0 last month. Now I have released a `2.0.0-alpha.1` version on npm. 2.0 includes the following changes:

1. TypeScript definition for Vue 2.5+
2. Magic dialogs wrapper mentioned in our previous conversation
3. Object as argument (just like what you said)

However, I am too busy to get the docs ready this month. If you were to try it, see the examples and tests for usage information. Please let me know if any problem encountered.

**Comment by Mike-Gibson-Advanced** [comment]
@hjkcai Hi, we're currently upgrading vue in our project so once that's complete I'll be able to look at version 2.0 alpha 1. Thanks for letting me know - looking forward to trying it out.

**Comment by ppn2** [comment]
Hi @hjkcai . I used the dialog and really liked it. However I could not make transition work. Can u please help me out there. I have to admit  am very new to vue, just working for last couple of days, so may be I am missing something.

**Comment by hjkcai** [comment]
@ppn2 See https://github.com/hjkcai/vue-modal-dialogs/blob/master/examples/dialogs.js

It is a little bit complicated right now. Just change the 'name' property to whatever you want. It works exactly the same as the <transition-group> component. If you are not familiar with <transition-group>, read vue's guide on transition first. 

https://vuejs.org/v2/guide/transitions.html

**Comment by hjkcai** [comment]
@Mike-Gibson-Advanced Hey! I released vue-modal-dialogs 2.0.0 just now. Have a try!

**Comment by Mike-Gibson-Advanced** [comment]
@hjkcai Hi, I finally got around to updating our project to vue 2.5 and updated vue-modal-dialogs to 2.0.0... it's working great.
This original issue is now fixed with your introduction of the `dialogs-wrapper` component.. good work. I think there could be a change or two to improve the unit testing story (for example, vue-modal-dialogs stores a list of `wrappers` globally and there's no way to destroy a registered wrapper) but it's working great in our project.. thanks!

**Comment by hjkcai** [comment]
@Mike-Gibson-Advanced You are right. There should have some way to destroy the wrappers. Otherwise memory leak may exist. I am planning the next release that has lots of improvements. I will include this one. Thanks for your suggestion. 

And by the way, recommend this little project to your friend if it is helpful ;D
